Edured-91: make auth configurable
Tiqr/eduid-app-android pull request #107
Opened 2023-06-14 13:22 UTC by IuliaSTANA

In order to avoid making multiple builds for different kinds of apps that work with different environments, the environment is decided at runtime (i.e. app process creation) instead of at build time.
The environment is a test setting that can be edited via a separate screen. This screen exists only for debug build types (app id `nl.eduid.testing`). Release versions of the app will not have this screen available and will *only* work with production environment.

When the environment is changed, the app will clear the app data tied to the environment and will require a force stop.

Github action changes:
1 - Release action can and should stay as is.

2 - PR build:
        = similar to the `build.yml` action
	= debug build signed with `testing.keystore`, required for deep linking to work
	= action can archives debug APK
	= nothing is uploaded to google play
	= action can check assembleRelease passes
	+ action needs a way to let the `app/build.gradle.kts` that the debug APK *should* be signed with `testing.keystore`. Right now relying on `CI` as an example. (A)
	- action doesn't need to archive *unsigned* release APK because it cannot be used for installation or any kind of QA/checking. An unsigned release APK can be made locally at any time, no need to archive it on a PR.

3 - New release candidate build:
	+ make debug *unsigned* bundle
	+ upload debug bundle to *new* google play store app

*Followup steps:*:
	+ New google play store app for nl.eduid.testing app
	+ New upload certificate for nl.eduid.testing app and github action configuration for this certificate
					OR
	= Reuse existing certificate and action variables declared for it.
	+ Once `nl.eduid.testing` app is created, uploaded to Google Play store, reviewed and approved, update the `https://domain.name/.well-known/assetlinks.json` so deep linking can work on the different environments.
	+ (A): a new variable/input parameter instead of `CI` so a distinction can safely be made between uploading a `nl.eduid.testing` bundle or archiving an `nl.eduid.testing` apk

NB: deep linking will not work until after the `assetlinks.json` file is updated with the Google Play store certificate signature
CC: @phavekes Please check that the values I guessed at in the different `auth_config.json` files from under `/app/src/main/res/raw` (for the test, acceptance & production environments) are correct.

https://github.com/Tiqr/eduid-app-android/assets/2356050/b2245502-2f2d-4711-b5a2-60ec421215f9

2023-06-15 07:37 UTC, dzolnai approved these changes

2023-06-16 07:51 UTC, phavekes requested changes

2023-06-16 07:51 UTC, phavekes commented on app/src/main/res/raw/auth_config_acceptance.json
> +  "client_id": "dev.egeniq.nl",
the clientId will be `acc.eduid.nl`

2023-06-16 07:51 UTC, phavekes commented on app/src/main/res/raw/auth_config.json
> +  "client_id": "dev.egeniq.nl",
the clientId will be `eduid.nl`

2023-06-16 07:51 UTC, phavekes commented on app/src/main/res/raw/auth_config_test.json
> +  "client_id": "dev.egeniq.nl",
the clientId will be `test.eduid.nl`

2023-06-19 07:16 UTC, phavekes commented
Why is the same clientid set in both `app/src/main/kotlin/nl/eduid/env/Environment.kt` and `app/src/main/res/raw/auth_config.json` ?

2023-06-22 08:30 UTC, phavekes approved these changes

2023-06-22 08:35 UTC, merged