Update submodule
Tiqr/eduid-app-android pull request #45
Opened 2022-10-20 12:08 UTC by dzolnai

2022-10-20 12:08 UTC, welsinga approved these changes

2022-10-20 12:11 UTC, phavekes approved these changes

2022-10-20 12:18 UTC, phavekes requested changes
Can the build error be fixed?
```
/home/runner/work/eduid-app-android/eduid-app-android/app-core/data/src/main/java/org/tiqr/data/repository/AuthenticationRepository.kt: (146, 64): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?
```

2022-10-20 13:30 UTC, dzolnai commented
Fixed!

2022-10-21 08:13 UTC, phavekes approved these changes

2022-10-21 08:14 UTC, merged